<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
    </head>
    <body>
        <header>
            <?php if(Zend_Auth::getInstance()->hasIdentity()):?>
            <a href="<?php echo $this->url(array(
                'controller' =>'auth', 
                'action' =>'logout'),null, true
            );?>">Выход</a>
            <?php else:?>
            <a href="<?php echo $this->url(array(
                'controller' =>'auth', 
                'action' =>'login'),null, true
            );?>">Авторизация</a>
            <a href="<?php echo $this->url(array(
                'controller' =>'auth', 
                'action' =>'registered'),null, true
            );?>">Регистрация</a>
            <?php endif?>
        </header>
        <?php echo $this->layout()->content; ?>
    </body>
</html>